### ISSUE TITLE
Fixnum undefined on Ruby 3.2.0

### ISSUE THREAD

**Issue by Arcovion** [dasch/ruby-bencode#20]
I get this error:
```ruby
gems/ruby-3.2.0/gems/bencode-0.8.2/lib/bencode/parser.rb:53:in `parse_dict!': uninitialized constant BEncode::Parser::Fixnum (NameError)

        unless key.is_a? String or key.is_a? Fixnum
                                             ^^^^^^
```
From [this line](https://github.com/dasch/ruby-bencode/blob/master/lib/bencode/parser.rb#L54), since Fixnum and Bignum were deprecated in Ruby 2.4 and were [removed in Ruby 3.2.0](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/#:~:text=Removed%20constants).

The workaround is to do `Fixnum = Integer` before using this gem. 
I believe Fixnum and Bignum inherited from Integer, so it should be safe to simply substitute this line `s/Fixnum/Integer` without breaking compatibility on older rubies, but I haven't tested it.

**Comment by dasch** [comment]
Could you make a PR?
